# Generated by Django 4.1.4 on 2023-01-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book", options={"ordering": ["title", "author"]},
        ),
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
    ]
